"""create shelves table

Revision ID: 1f73a762cdb1
Revises: 0e146d5c37e4
Create Date: 2026-10-04 14:08:50.871983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f73a762cdb1'
down_revision: Union[str, Sequence[str], None] = '0e146d5c37e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelves_id'), 'shelves', ['id'], unique=False)
    op.create_index(op.f('ix_shelves_owner_id'), 'shelves', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelves_owner_id'), table_name='shelves')
    op.drop_index(op.f('ix_shelves_id'), table_name='shelves')
    op.drop_table('shelves')
    # ### end Alembic commands ###
