"""create lendings table

Revision ID: c0d2fc60c6d7
Revises: d7661574ccd9
Create Date: 2026-10-04 14:16:59.683686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d2fc60c6d7'
down_revision: Union[str, Sequence[str], None] = 'd7661574ccd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('lent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendings_active'), 'lendings', ['active'], unique=False)
    op.create_index(op.f('ix_lendings_book_id'), 'lendings', ['book_id'], unique=False)
    op.create_index(op.f('ix_lendings_borrower_id'), 'lendings', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_lendings_id'), 'lendings', ['id'], unique=False)
    op.create_index(op.f('ix_lendings_owner_id'), 'lendings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lendings_owner_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_borrower_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_book_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_active'), table_name='lendings')
    op.drop_table('lendings')
    # ### end Alembic commands ###
