"""create shelf shares table

Revision ID: c9155a158a9d
Revises: 8d9cd731e2bf
Create Date: 2026-10-04 14:13:18.975175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9155a158a9d'
down_revision: Union[str, Sequence[str], None] = '8d9cd731e2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'user_id', name='uq_shelf_share')
    )
    op.create_index(op.f('ix_shelf_shares_id'), 'shelf_shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_shares_id'), table_name='shelf_shares')
    op.drop_table('shelf_shares')
    # ### end Alembic commands ###
